# General
name: Restful Objects
description: "domain driven design, apache&nbsp;isis, restful&nbsp;objects, naked&nbsp;objects, agile, tdd"
#url: http://localhost:4000

exclude: [_README, _zzz, Gemfile.lock]

markdown: kramdown
highlighter: rouge

paginate: 50
permalink: /:year/:month/:day/:title/

# Social share and comments.
#disqus-id: danhaywood
#twitter: dkhaywood
#github: danhaywood
#google: +DanHaywood

#linkedin: dkhaywood
#youtube: TheDanHaywood


# RSS feed
#rss-feed-limit: 10
#rss-show-full: "no"



asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
    - hardbreaks!
